#!/usr/bin/env python3
# ============================================================
# FRB–CMB DIPOLE CORRELATION & ALIGNMENT TEST
# ============================================================
# this script measures whether the frb sky anisotropy
# (dipole amplitude, dipole direction, and axis projection)
# correlates with the cosmic microwave background (cmb) dipole
# generated by the solar-system barycentric motion.
#
# tests performed:
#   1. frb dipole direction in galactic coordinates
#   2. angular separation from the cmb dipole
#   3. projection of frb unit vectors onto cmb dipole axis
#   4. comparison with isotropic monte-carlo nulls
#   5. correlation statistics:
#       - dipole amplitude correlation
#       - axis alignment probability
#       - projection-significance
#
# input:
#   frbs.csv containing: ra, dec, z_est
#
# output:
#   printed scientific analysis
# ============================================================

import numpy as np
import pandas as pd
from astropy.coordinates import SkyCoord
import astropy.units as u

# ------------------------------------------------------------
# CONFIG
# ------------------------------------------------------------

CATALOG_FILE = r"C:\Users\ratec\Documents\CrossLayerPhysics\frbs.csv"
N_MC = 20000

# CMB kinetic dipole direction (Planck 2018)
# galactic coordinates:
CMB_L = 264.0   # deg
CMB_B = 48.0    # deg

# unified axis (galactic)
UNIFIED_L = 159.85
UNIFIED_B = -0.51

# ------------------------------------------------------------
# helpers
# ------------------------------------------------------------

def load_frbs(path):
    df = pd.read_csv(path)
    df = df.dropna(subset=["ra", "dec"])
    return df

def dipole_axis_r(ra_deg, dec_deg):
    """compute dipole amplitude r and dipole axis in galactic coords."""
    ra = np.deg2rad(ra_deg)
    dec = np.deg2rad(dec_deg)

    x = np.cos(dec) * np.cos(ra)
    y = np.cos(dec) * np.sin(ra)
    z = np.sin(dec)

    M = np.vstack([x, y, z]).T
    mean_vec = M.mean(axis=0)
    r = np.linalg.norm(mean_vec)

    if r == 0:
        axis = np.array([1.0, 0.0, 0.0])
    else:
        axis = mean_vec / r

    c = SkyCoord(
        x=axis[0], y=axis[1], z=axis[2],
        frame="icrs", representation_type="cartesian"
    )
    g = c.galactic
    return g.l.deg, g.b.deg, float(r)

def angsep(l1, b1, l2, b2):
    c1 = SkyCoord(l1*u.deg, b1*u.deg, frame="galactic")
    c2 = SkyCoord(l2*u.deg, b2*u.deg, frame="galactic")
    return c1.separation(c2).deg

def projection_statistic(ra_deg, dec_deg, l_axis, b_axis):
    """mean projection of frb unit vectors onto a given galactic axis."""
    frb = SkyCoord(ra=ra_deg*u.deg, dec=dec_deg*u.deg, frame="icrs")
    frb_g = frb.galactic

    frb_vec = np.vstack([
        np.cos(frb_g.b.rad) * np.cos(frb_g.l.rad),
        np.cos(frb_g.b.rad) * np.sin(frb_g.l.rad),
        np.sin(frb_g.b.rad)
    ]).T

    ax = SkyCoord(l=l_axis*u.deg, b=b_axis*u.deg, frame="galactic")
    ax_vec = np.array([
        np.cos(ax.b.rad) * np.cos(ax.l.rad),
        np.cos(ax.b.rad) * np.sin(ax.l.rad),
        np.sin(ax.b.rad)
    ])

    proj = frb_vec @ ax_vec
    return proj.mean(), proj.std()

def isotropic_mock(n):
    """sample n isotropic sky directions."""
    u1 = np.random.random(n)
    u2 = np.random.random(n)
    ra = 360 * u1
    dec = np.rad2deg(np.arcsin(2*u2 - 1))
    return ra, dec

# ------------------------------------------------------------
# monte-carlo
# ------------------------------------------------------------

def mc_projection_null(n_frb, l_axis, b_axis, n_mc=N_MC):
    """generate projection significance distribution under isotropy."""
    proj_vals = np.empty(n_mc)
    for i in range(n_mc):
        ra_mock, dec_mock = isotropic_mock(n_frb)
        m, _ = projection_statistic(ra_mock, dec_mock, l_axis, b_axis)
        proj_vals[i] = m
    return proj_vals

# ------------------------------------------------------------
# main
# ------------------------------------------------------------

def main():
    print("===================================================")
    print("FRB–CMB DIPOLE CORRELATION TEST")
    print("===================================================\n")

    df = load_frbs(CATALOG_FILE)
    ra = df["ra"].values
    dec = df["dec"].values
    n = len(df)

    print(f"loaded FRBs: {n}\n")

    # --------------------------------------------------------
    # real frb dipole
    # --------------------------------------------------------
    l_frb, b_frb, r_frb = dipole_axis_r(ra, dec)

    print("============= REAL FRB SKY =============")
    print(f"FRB dipole axis (galactic):")
    print(f"  l = {l_frb:.3f} deg")
    print(f"  b = {b_frb:.3f} deg")
    print(f"dipole amplitude r = {r_frb:.4f}")

    sep_cmb = angsep(l_frb, b_frb, CMB_L, CMB_B)
    sep_unified = angsep(l_frb, b_frb, UNIFIED_L, UNIFIED_B)

    print(f"angular separation from CMB dipole = {sep_cmb:.3f} deg")
    print(f"angular separation from unified axis = {sep_unified:.3f} deg\n")

    # --------------------------------------------------------
    # projection test: do frbs align with cmb dipole?
    # --------------------------------------------------------
    proj_real, proj_std = projection_statistic(ra, dec, CMB_L, CMB_B)
    print("FRB projection onto CMB dipole axis:")
    print(f"  mean projection = {proj_real:.5f}")
    print(f"  std projection  = {proj_std:.5f}\n")

    print("running isotropic monte-carlo for projection null...")
    proj_null = mc_projection_null(n, CMB_L, CMB_B)
    p_proj = np.mean(proj_null >= proj_real)

    print("============= PROJECTION NULL =============")
    print(f"<proj>_iso ≈ {proj_null.mean():.6f}")
    print(f"std(proj)_iso ≈ {proj_null.std():.6f}")
    print(f"P(proj_null >= proj_real) = {p_proj:.5f}\n")

    # --------------------------------------------------------
    # combined correlation statistic
    # --------------------------------------------------------
    print("===================================================")
    print("scientific verdict")
    print("===================================================")

    # interpret alignment
    if sep_cmb < 25 and p_proj < 0.05:
        print(
            "the frb dipole lies within ~25° of the CMB dipole and the projection "
            "onto the CMB axis is significantly larger than isotropy. "
            "this suggests a statistically meaningful coupling between frb "
            "anisotropy and the barycentric motion encoded in the CMB dipole."
        )
    elif sep_cmb < 25 and p_proj >= 0.05:
        print(
            "the frb dipole is close to the CMB dipole direction, but the projection "
            "test does not show a significant enhancement relative to isotropy. "
            "this indicates geometric proximity without strong statistical coupling."
        )
    elif sep_cmb >= 25 and p_proj < 0.05:
        print(
            "the frb dipole is not close to the CMB dipole, but the projection "
            "significance is unusually high. this hints at a weak or higher-order "
            "relationship rather than direct axis alignment."
        )
    else:
        print(
            "the frb dipole direction is not close to the CMB dipole and the "
            "projection significance is consistent with isotropy. "
            "no evidence for frb–cmb dipole correlation is found."
        )

    print("---------------------------------------------------")
    print("analysis complete.")
    print("===================================================\n")


if __name__ == "__main__":
    main()
