#!/usr/bin/env python3
# ============================================================
# FRB SUPERGALACTIC-PLANE MASK SHELL TEST
# ============================================================
# this test checks whether the FRB radial shell anisotropy
# persists after masking around the supergalactic plane (SGB = 0),
# which traces the local large-scale structure (Virgo supercluster).
#
# bins: 0–10°, 10–25°, 25–40°, 40–90°
# χ² vs isotropic expectation computed for:
#   - full sample
#   - |SGB| >= 10°
#   - |SGB| >= 20°
#   - |SGB| >= 30°
#
# if the anisotropy survives high-SGB cuts, it is NOT tied to
# local supercluster structure → pushes origin to deeper scales.
# ============================================================

import numpy as np
import pandas as pd
from astropy.coordinates import SkyCoord
import astropy.units as u

CATALOG_FILE = r"C:\Users\ratec\Documents\CrossLayerPhysics\frbs.csv"

# unified axis from previous analysis
UNIFIED_L = 159.85
UNIFIED_B = -0.51

# shell bin edges (deg)
BINS = np.array([0, 10, 25, 40, 90])


# ------------------------------------------------------------
# helpers
# ------------------------------------------------------------

def load_catalog(path):
    df = pd.read_csv(path)
    df = df.dropna(subset=["ra", "dec"])
    return df


def theta_from_axis(ra_deg, dec_deg, L0=UNIFIED_L, B0=UNIFIED_B):
    c = SkyCoord(ra=ra_deg*u.deg, dec=dec_deg*u.deg, frame='icrs')
    axis = SkyCoord(l=L0*u.deg, b=B0*u.deg, frame='galactic')
    # convert axis to ICRS for separation
    axis_icrs = axis.icrs
    theta = c.separation(axis_icrs).deg
    return theta


def chi2_test(theta):
    # observed counts
    n = len(theta)
    hist, _ = np.histogram(theta, bins=BINS)

    # isotropic expectation: area fraction of spherical cap
    # P(theta<Δ) = (1 - cosΔ)/2
    def Pcap(x): return (1 - np.cos(np.deg2rad(x))) / 2

    exp = np.zeros_like(hist, dtype=float)
    for i in range(len(hist)):
        exp[i] = n * (Pcap(BINS[i+1]) - Pcap(BINS[i]))

    # chi²
    chi2 = np.sum((hist - exp)**2 / exp)

    # p-value from chi² with dof = bins-1 = 3
    from scipy.stats import chi2 as chi2dist
    p = 1 - chi2dist.cdf(chi2, df=3)

    return hist, exp, chi2, p


def compute_supergalactic_lat(ra, dec):
    c = SkyCoord(ra=ra*u.deg, dec=dec*u.deg, frame='icrs')
    sg = c.transform_to("supergalactic")
    return sg.sgb.deg  # supergalactic latitude


# ------------------------------------------------------------
# main
# ------------------------------------------------------------

def analyse_subset(label, theta_subset):
    hist, exp, chi2, p = chi2_test(theta_subset)

    print(f"\nsubset: {label}")
    print(f"n_FRB = {len(theta_subset)}")
    for i in range(len(hist)):
        print(f"band {BINS[i]:3.0f}°–{BINS[i+1]:3.0f}° : "
              f"obs = {hist[i]:4d}, exp_iso = {exp[i]:7.2f}, "
              f"ratio = {hist[i]/exp[i]:5.2f}")
    print(f"total chi² (vs isotropy) = {chi2:.2f} (dof=3)")
    print(f"p-value (isotropic null) = {p:.3e}")


def main():
    print("===================================================")
    print("FRB SUPERGALACTIC-PLANE MASK SHELL TEST")
    print("===================================================\n")

    df = load_catalog(CATALOG_FILE)
    print(f"loaded FRBs with valid positions: {len(df)}")

    ra = df["ra"].values
    dec = df["dec"].values

    # compute angles from unified axis
    theta = theta_from_axis(ra, dec)

    # compute supergalactic latitude
    sgb = compute_supergalactic_lat(ra, dec)

    # analyse full sample
    analyse_subset("all (no |SGB| cut)", theta)

    # |SGB| >= 10
    mask10 = np.abs(sgb) >= 10
    analyse_subset("|SGB| >= 10°", theta[mask10])

    # |SGB| >= 20
    mask20 = np.abs(sgb) >= 20
    analyse_subset("|SGB| >= 20°", theta[mask20])

    # |SGB| >= 30
    mask30 = np.abs(sgb) >= 30
    analyse_subset("|SGB| >= 30°", theta[mask30])

    print("\n---------------- scientific verdict ----------------")

    print(
        "if the layered shell excess (particularly the 25°–40° band) "
        "remains significant after removing |SGB| >= 20° or |SGB| >= 30°, "
        "then the anisotropy is not tied to the local supercluster plane.\n"
        "this would imply that the structure is deeper than ~30–50 Mpc "
        "and therefore not generated by Virgo-supercluster geometry.\n"
        "if the signal collapses with SGB masking, it indicates that "
        "the anisotropy is contributed or dominated by local large-scale structure."
    )

    print("---------------------------------------------------")
    print("analysis complete.")
    print("===================================================\n")


if __name__ == "__main__":
    main()
